#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataAccessLayer;

namespace DataAccessLayer	
{
	public partial class EntitiesModel : OpenAccessContext, IEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"Pramirez_escuelaConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public EntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Tutor> Tutors 
		{
			get
			{
				return this.GetAll<Tutor>();
			}
		}
		
		public IQueryable<Tramite> Tramites 
		{
			get
			{
				return this.GetAll<Tramite>();
			}
		}
		
		public IQueryable<Telefono> Telefonos 
		{
			get
			{
				return this.GetAll<Telefono>();
			}
		}
		
		public IQueryable<Tarea> Tareas 
		{
			get
			{
				return this.GetAll<Tarea>();
			}
		}
		
		public IQueryable<Solicitud_tramite> Solicitud_tramites 
		{
			get
			{
				return this.GetAll<Solicitud_tramite>();
			}
		}
		
		public IQueryable<Servicio> Servicios 
		{
			get
			{
				return this.GetAll<Servicio>();
			}
		}
		
		public IQueryable<Rol> Rols 
		{
			get
			{
				return this.GetAll<Rol>();
			}
		}
		
		public IQueryable<Proveedor> Proveedors 
		{
			get
			{
				return this.GetAll<Proveedor>();
			}
		}
		
		public IQueryable<Profesor> Profesors 
		{
			get
			{
				return this.GetAll<Profesor>();
			}
		}
		
		public IQueryable<Persona> Personas 
		{
			get
			{
				return this.GetAll<Persona>();
			}
		}
		
		public IQueryable<Periodo> Periodos 
		{
			get
			{
				return this.GetAll<Periodo>();
			}
		}
		
		public IQueryable<Pago> Pagos 
		{
			get
			{
				return this.GetAll<Pago>();
			}
		}
		
		public IQueryable<Nivel_educativo> Nivel_educativos 
		{
			get
			{
				return this.GetAll<Nivel_educativo>();
			}
		}
		
		public IQueryable<Modulo> Modulos 
		{
			get
			{
				return this.GetAll<Modulo>();
			}
		}
		
		public IQueryable<Mes_escolar> Mes_escolars 
		{
			get
			{
				return this.GetAll<Mes_escolar>();
			}
		}
		
		public IQueryable<Mes_actividad> Mes_actividads 
		{
			get
			{
				return this.GetAll<Mes_actividad>();
			}
		}
		
		public IQueryable<Mensajes_global_borrar> Mensajes_global_borrars 
		{
			get
			{
				return this.GetAll<Mensajes_global_borrar>();
			}
		}
		
		public IQueryable<Mensaje> Mensajes 
		{
			get
			{
				return this.GetAll<Mensaje>();
			}
		}
		
		public IQueryable<Medico> Medicos 
		{
			get
			{
				return this.GetAll<Medico>();
			}
		}
		
		public IQueryable<Materia_prerrequisito> Materia_prerrequisitos 
		{
			get
			{
				return this.GetAll<Materia_prerrequisito>();
			}
		}
		
		public IQueryable<Materia_grupo> Materia_grupos 
		{
			get
			{
				return this.GetAll<Materia_grupo>();
			}
		}
		
		public IQueryable<Materium> Materia 
		{
			get
			{
				return this.GetAll<Materium>();
			}
		}
		
		public IQueryable<Literal> Literals 
		{
			get
			{
				return this.GetAll<Literal>();
			}
		}
		
		public IQueryable<Liga> Ligas 
		{
			get
			{
				return this.GetAll<Liga>();
			}
		}
		
		public IQueryable<Inasistencium> Inasistencia 
		{
			get
			{
				return this.GetAll<Inasistencium>();
			}
		}
		
		public IQueryable<Horario> Horarios 
		{
			get
			{
				return this.GetAll<Horario>();
			}
		}
		
		public IQueryable<Historial_medico> Historial_medicos 
		{
			get
			{
				return this.GetAll<Historial_medico>();
			}
		}
		
		public IQueryable<Grupo> Grupos 
		{
			get
			{
				return this.GetAll<Grupo>();
			}
		}
		
		public IQueryable<Foto_alumno> Foto_alumnos 
		{
			get
			{
				return this.GetAll<Foto_alumno>();
			}
		}
		
		public IQueryable<Domicilio> Domicilios 
		{
			get
			{
				return this.GetAll<Domicilio>();
			}
		}
		
		public IQueryable<Detalle_horario> Detalle_horarios 
		{
			get
			{
				return this.GetAll<Detalle_horario>();
			}
		}
		
		public IQueryable<Destinatario> Destinatarios 
		{
			get
			{
				return this.GetAll<Destinatario>();
			}
		}
		
		public IQueryable<Circulare> Circulares 
		{
			get
			{
				return this.GetAll<Circulare>();
			}
		}
		
		public IQueryable<Calificacion_parcial> Calificacion_parcials 
		{
			get
			{
				return this.GetAll<Calificacion_parcial>();
			}
		}
		
		public IQueryable<Calendario_escolar> Calendario_escolars 
		{
			get
			{
				return this.GetAll<Calendario_escolar>();
			}
		}
		
		public IQueryable<Alumno> Alumnos 
		{
			get
			{
				return this.GetAll<Alumno>();
			}
		}
		
		public IQueryable<Administrativo> Administrativos 
		{
			get
			{
				return this.GetAll<Administrativo>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Tutor> Tutors
		{
			get;
		}
		IQueryable<Tramite> Tramites
		{
			get;
		}
		IQueryable<Telefono> Telefonos
		{
			get;
		}
		IQueryable<Tarea> Tareas
		{
			get;
		}
		IQueryable<Solicitud_tramite> Solicitud_tramites
		{
			get;
		}
		IQueryable<Servicio> Servicios
		{
			get;
		}
		IQueryable<Rol> Rols
		{
			get;
		}
		IQueryable<Proveedor> Proveedors
		{
			get;
		}
		IQueryable<Profesor> Profesors
		{
			get;
		}
		IQueryable<Persona> Personas
		{
			get;
		}
		IQueryable<Periodo> Periodos
		{
			get;
		}
		IQueryable<Pago> Pagos
		{
			get;
		}
		IQueryable<Nivel_educativo> Nivel_educativos
		{
			get;
		}
		IQueryable<Modulo> Modulos
		{
			get;
		}
		IQueryable<Mes_escolar> Mes_escolars
		{
			get;
		}
		IQueryable<Mes_actividad> Mes_actividads
		{
			get;
		}
		IQueryable<Mensajes_global_borrar> Mensajes_global_borrars
		{
			get;
		}
		IQueryable<Mensaje> Mensajes
		{
			get;
		}
		IQueryable<Medico> Medicos
		{
			get;
		}
		IQueryable<Materia_prerrequisito> Materia_prerrequisitos
		{
			get;
		}
		IQueryable<Materia_grupo> Materia_grupos
		{
			get;
		}
		IQueryable<Materium> Materia
		{
			get;
		}
		IQueryable<Literal> Literals
		{
			get;
		}
		IQueryable<Liga> Ligas
		{
			get;
		}
		IQueryable<Inasistencium> Inasistencia
		{
			get;
		}
		IQueryable<Horario> Horarios
		{
			get;
		}
		IQueryable<Historial_medico> Historial_medicos
		{
			get;
		}
		IQueryable<Grupo> Grupos
		{
			get;
		}
		IQueryable<Foto_alumno> Foto_alumnos
		{
			get;
		}
		IQueryable<Domicilio> Domicilios
		{
			get;
		}
		IQueryable<Detalle_horario> Detalle_horarios
		{
			get;
		}
		IQueryable<Destinatario> Destinatarios
		{
			get;
		}
		IQueryable<Circulare> Circulares
		{
			get;
		}
		IQueryable<Calificacion_parcial> Calificacion_parcials
		{
			get;
		}
		IQueryable<Calendario_escolar> Calendario_escolars
		{
			get;
		}
		IQueryable<Alumno> Alumnos
		{
			get;
		}
		IQueryable<Administrativo> Administrativos
		{
			get;
		}
	}
}
namespace DataAccessLayer	
{
	public partial class Tutor
	{
		private long _iD_TUTOR;
		public virtual long ID_TUTOR
		{
			get
			{
				return this._iD_TUTOR;
			}
			set
			{
				this._iD_TUTOR = value;
			}
		}
		
		private Persona _persona;
		public virtual Persona Persona
		{
			get
			{
				return this._persona;
			}
			set
			{
				this._persona = value;
			}
		}
		
		private IList<Circulare> _circulares = new List<Circulare>();
		public virtual IList<Circulare> Circulares
		{
			get
			{
				return this._circulares;
			}
		}
		
		private IList<Alumno> _alumnos = new List<Alumno>();
		public virtual IList<Alumno> Alumnos
		{
			get
			{
				return this._alumnos;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Tramite
	{
		private long _iD_TRAMITE;
		public virtual long ID_TRAMITE
		{
			get
			{
				return this._iD_TRAMITE;
			}
			set
			{
				this._iD_TRAMITE = value;
			}
		}
		
		private string _nOMBRE;
		public virtual string NOMBRE
		{
			get
			{
				return this._nOMBRE;
			}
			set
			{
				this._nOMBRE = value;
			}
		}
		
		private string _cOSTO;
		public virtual string COSTO
		{
			get
			{
				return this._cOSTO;
			}
			set
			{
				this._cOSTO = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private IList<Solicitud_tramite> _solicitud_tramites = new List<Solicitud_tramite>();
		public virtual IList<Solicitud_tramite> Solicitud_tramites
		{
			get
			{
				return this._solicitud_tramites;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Telefono
	{
		private Char _tIPO_TELEFONO;
		public virtual Char TIPO_TELEFONO
		{
			get
			{
				return this._tIPO_TELEFONO;
			}
			set
			{
				this._tIPO_TELEFONO = value;
			}
		}
		
		private string _cODIGO_PAIS;
		public virtual string CODIGO_PAIS
		{
			get
			{
				return this._cODIGO_PAIS;
			}
			set
			{
				this._cODIGO_PAIS = value;
			}
		}
		
		private string _cODIGO_CIUDAD;
		public virtual string CODIGO_CIUDAD
		{
			get
			{
				return this._cODIGO_CIUDAD;
			}
			set
			{
				this._cODIGO_CIUDAD = value;
			}
		}
		
		private string _nUMERO;
		public virtual string NUMERO
		{
			get
			{
				return this._nUMERO;
			}
			set
			{
				this._nUMERO = value;
			}
		}
		
		private long _iD_PERSONA;
		public virtual long ID_PERSONA
		{
			get
			{
				return this._iD_PERSONA;
			}
			set
			{
				this._iD_PERSONA = value;
			}
		}
		
		private Persona _persona;
		public virtual Persona Persona
		{
			get
			{
				return this._persona;
			}
			set
			{
				this._persona = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Tarea
	{
		private long _iD_PROFESOR;
		public virtual long ID_PROFESOR
		{
			get
			{
				return this._iD_PROFESOR;
			}
			set
			{
				this._iD_PROFESOR = value;
			}
		}
		
		private long _iD_GRUPO;
		public virtual long ID_GRUPO
		{
			get
			{
				return this._iD_GRUPO;
			}
			set
			{
				this._iD_GRUPO = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private long _iD_TAREA;
		public virtual long ID_TAREA
		{
			get
			{
				return this._iD_TAREA;
			}
			set
			{
				this._iD_TAREA = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private string _pATH_ARCHIVO_ADJUNTO;
		public virtual string PATH_ARCHIVO_ADJUNTO
		{
			get
			{
				return this._pATH_ARCHIVO_ADJUNTO;
			}
			set
			{
				this._pATH_ARCHIVO_ADJUNTO = value;
			}
		}
		
		private DateTime? _fECHA;
		public virtual DateTime? FECHA
		{
			get
			{
				return this._fECHA;
			}
			set
			{
				this._fECHA = value;
			}
		}
		
		private Profesor _profesor;
		public virtual Profesor Profesor
		{
			get
			{
				return this._profesor;
			}
			set
			{
				this._profesor = value;
			}
		}
		
		private Grupo _grupo;
		public virtual Grupo Grupo
		{
			get
			{
				return this._grupo;
			}
			set
			{
				this._grupo = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Solicitud_tramite
	{
		private string _cODIGO_ALUMNO_EN_INSTITUCION;
		public virtual string CODIGO_ALUMNO_EN_INSTITUCION
		{
			get
			{
				return this._cODIGO_ALUMNO_EN_INSTITUCION;
			}
			set
			{
				this._cODIGO_ALUMNO_EN_INSTITUCION = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private long _iD_TRAMITE;
		public virtual long ID_TRAMITE
		{
			get
			{
				return this._iD_TRAMITE;
			}
			set
			{
				this._iD_TRAMITE = value;
			}
		}
		
		private DateTime? _fECHA_SOLICITUD;
		public virtual DateTime? FECHA_SOLICITUD
		{
			get
			{
				return this._fECHA_SOLICITUD;
			}
			set
			{
				this._fECHA_SOLICITUD = value;
			}
		}
		
		private System.Nullable<System.Char> _sTATUS_TRAMITE;
		public virtual System.Nullable<System.Char> STATUS_TRAMITE
		{
			get
			{
				return this._sTATUS_TRAMITE;
			}
			set
			{
				this._sTATUS_TRAMITE = value;
			}
		}
		
		private long? _iD_ADMINISTRATIVO;
		public virtual long? ID_ADMINISTRATIVO
		{
			get
			{
				return this._iD_ADMINISTRATIVO;
			}
			set
			{
				this._iD_ADMINISTRATIVO = value;
			}
		}
		
		private Alumno _alumno;
		public virtual Alumno Alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno = value;
			}
		}
		
		private Tramite _tramite;
		public virtual Tramite Tramite
		{
			get
			{
				return this._tramite;
			}
			set
			{
				this._tramite = value;
			}
		}
		
		private Administrativo _administrativo;
		public virtual Administrativo Administrativo
		{
			get
			{
				return this._administrativo;
			}
			set
			{
				this._administrativo = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Servicio
	{
		private long _iD_SERVICIO;
		public virtual long ID_SERVICIO
		{
			get
			{
				return this._iD_SERVICIO;
			}
			set
			{
				this._iD_SERVICIO = value;
			}
		}
		
		private string _nOMBRE;
		public virtual string NOMBRE
		{
			get
			{
				return this._nOMBRE;
			}
			set
			{
				this._nOMBRE = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private string _cOSTO;
		public virtual string COSTO
		{
			get
			{
				return this._cOSTO;
			}
			set
			{
				this._cOSTO = value;
			}
		}
		
		private System.Nullable<System.Char> _sTATUS;
		public virtual System.Nullable<System.Char> STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private IList<Proveedor> _proveedors = new List<Proveedor>();
		public virtual IList<Proveedor> Proveedors
		{
			get
			{
				return this._proveedors;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Rol
	{
		private long _iD_ROL;
		public virtual long ID_ROL
		{
			get
			{
				return this._iD_ROL;
			}
			set
			{
				this._iD_ROL = value;
			}
		}
		
		private string _nOMBRE_ROL;
		public virtual string NOMBRE_ROL
		{
			get
			{
				return this._nOMBRE_ROL;
			}
			set
			{
				this._nOMBRE_ROL = value;
			}
		}
		
		private string _dESCRIPCION_ROL;
		public virtual string DESCRIPCION_ROL
		{
			get
			{
				return this._dESCRIPCION_ROL;
			}
			set
			{
				this._dESCRIPCION_ROL = value;
			}
		}
		
		private System.Nullable<System.Char> _sTATUS;
		public virtual System.Nullable<System.Char> STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private IList<Persona> _personas = new List<Persona>();
		public virtual IList<Persona> Personas
		{
			get
			{
				return this._personas;
			}
		}
		
		private IList<Modulo> _modulos = new List<Modulo>();
		public virtual IList<Modulo> Modulos
		{
			get
			{
				return this._modulos;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Proveedor
	{
		private long _iD_PROVEEDOR;
		public virtual long ID_PROVEEDOR
		{
			get
			{
				return this._iD_PROVEEDOR;
			}
			set
			{
				this._iD_PROVEEDOR = value;
			}
		}
		
		private string _nOMBRE_PROVEEDOR;
		public virtual string NOMBRE_PROVEEDOR
		{
			get
			{
				return this._nOMBRE_PROVEEDOR;
			}
			set
			{
				this._nOMBRE_PROVEEDOR = value;
			}
		}
		
		private System.Nullable<System.Char> _tIPO_PROVEEDOR;
		public virtual System.Nullable<System.Char> TIPO_PROVEEDOR
		{
			get
			{
				return this._tIPO_PROVEEDOR;
			}
			set
			{
				this._tIPO_PROVEEDOR = value;
			}
		}
		
		private System.Nullable<System.Char> _iNTERNO_EXTERNO;
		public virtual System.Nullable<System.Char> INTERNO_EXTERNO
		{
			get
			{
				return this._iNTERNO_EXTERNO;
			}
			set
			{
				this._iNTERNO_EXTERNO = value;
			}
		}
		
		private System.Nullable<System.Char> _sTATUS;
		public virtual System.Nullable<System.Char> STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private IList<Servicio> _servicios = new List<Servicio>();
		public virtual IList<Servicio> Servicios
		{
			get
			{
				return this._servicios;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Profesor
	{
		private long _iD_PROFESOR;
		public virtual long ID_PROFESOR
		{
			get
			{
				return this._iD_PROFESOR;
			}
			set
			{
				this._iD_PROFESOR = value;
			}
		}
		
		private long? _iD_PERSONA;
		public virtual long? ID_PERSONA
		{
			get
			{
				return this._iD_PERSONA;
			}
			set
			{
				this._iD_PERSONA = value;
			}
		}
		
		private long? _iD_NIVEL;
		public virtual long? ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private Persona _persona;
		public virtual Persona Persona
		{
			get
			{
				return this._persona;
			}
			set
			{
				this._persona = value;
			}
		}
		
		private Nivel_educativo _nivel_educativo;
		public virtual Nivel_educativo Nivel_educativo
		{
			get
			{
				return this._nivel_educativo;
			}
			set
			{
				this._nivel_educativo = value;
			}
		}
		
		private IList<Tarea> _tareas = new List<Tarea>();
		public virtual IList<Tarea> Tareas
		{
			get
			{
				return this._tareas;
			}
		}
		
		private IList<Materia_grupo> _materia_grupos = new List<Materia_grupo>();
		public virtual IList<Materia_grupo> Materia_grupos
		{
			get
			{
				return this._materia_grupos;
			}
		}
		
		private IList<Materium> _materia = new List<Materium>();
		public virtual IList<Materium> Materia
		{
			get
			{
				return this._materia;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Persona
	{
		private long _iD_PERSONA;
		public virtual long ID_PERSONA
		{
			get
			{
				return this._iD_PERSONA;
			}
			set
			{
				this._iD_PERSONA = value;
			}
		}
		
		private string _nOMBRE;
		public virtual string NOMBRE
		{
			get
			{
				return this._nOMBRE;
			}
			set
			{
				this._nOMBRE = value;
			}
		}
		
		private string _aPELLIDO_PATERNO;
		public virtual string APELLIDO_PATERNO
		{
			get
			{
				return this._aPELLIDO_PATERNO;
			}
			set
			{
				this._aPELLIDO_PATERNO = value;
			}
		}
		
		private string _aPELLIDO_MATERNO;
		public virtual string APELLIDO_MATERNO
		{
			get
			{
				return this._aPELLIDO_MATERNO;
			}
			set
			{
				this._aPELLIDO_MATERNO = value;
			}
		}
		
		private string _eMAIL;
		public virtual string EMAIL
		{
			get
			{
				return this._eMAIL;
			}
			set
			{
				this._eMAIL = value;
			}
		}
		
		private System.Nullable<System.Char> _sEXO;
		public virtual System.Nullable<System.Char> SEXO
		{
			get
			{
				return this._sEXO;
			}
			set
			{
				this._sEXO = value;
			}
		}
		
		private string _nACIONALIDAD;
		public virtual string NACIONALIDAD
		{
			get
			{
				return this._nACIONALIDAD;
			}
			set
			{
				this._nACIONALIDAD = value;
			}
		}
		
		private string _lOG_NAME;
		public virtual string LOG_NAME
		{
			get
			{
				return this._lOG_NAME;
			}
			set
			{
				this._lOG_NAME = value;
			}
		}
		
		private string _pASSWORD;
		public virtual string PASSWORD
		{
			get
			{
				return this._pASSWORD;
			}
			set
			{
				this._pASSWORD = value;
			}
		}
		
		private DateTime? _fECHA_INGRESO;
		public virtual DateTime? FECHA_INGRESO
		{
			get
			{
				return this._fECHA_INGRESO;
			}
			set
			{
				this._fECHA_INGRESO = value;
			}
		}
		
		private System.Nullable<System.Char> _sTATUS;
		public virtual System.Nullable<System.Char> STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private long? _iD_ROL;
		public virtual long? ID_ROL
		{
			get
			{
				return this._iD_ROL;
			}
			set
			{
				this._iD_ROL = value;
			}
		}
		
		private Rol _rol;
		public virtual Rol Rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				this._rol = value;
			}
		}
		
		private IList<Telefono> _telefonos = new List<Telefono>();
		public virtual IList<Telefono> Telefonos
		{
			get
			{
				return this._telefonos;
			}
		}
		
		private IList<Profesor> _profesors = new List<Profesor>();
		public virtual IList<Profesor> Profesors
		{
			get
			{
				return this._profesors;
			}
		}
		
		private IList<Domicilio> _domicilios = new List<Domicilio>();
		public virtual IList<Domicilio> Domicilios
		{
			get
			{
				return this._domicilios;
			}
		}
		
		private IList<Destinatario> _destinatarios = new List<Destinatario>();
		public virtual IList<Destinatario> Destinatarios
		{
			get
			{
				return this._destinatarios;
			}
		}
		
		private IList<Alumno> _alumnos = new List<Alumno>();
		public virtual IList<Alumno> Alumnos
		{
			get
			{
				return this._alumnos;
			}
		}
		
		private IList<Administrativo> _administrativos = new List<Administrativo>();
		public virtual IList<Administrativo> Administrativos
		{
			get
			{
				return this._administrativos;
			}
		}
		
		private Tutor _tutor;
		public virtual Tutor Tutor
		{
			get
			{
				return this._tutor;
			}
			set
			{
				this._tutor = value;
			}
		}
		
		private Medico _medico;
		public virtual Medico Medico
		{
			get
			{
				return this._medico;
			}
			set
			{
				this._medico = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Periodo
	{
		private long _iD_PERIODO;
		public virtual long ID_PERIODO
		{
			get
			{
				return this._iD_PERIODO;
			}
			set
			{
				this._iD_PERIODO = value;
			}
		}
		
		private DateTime? _fECHA_INICIO;
		public virtual DateTime? FECHA_INICIO
		{
			get
			{
				return this._fECHA_INICIO;
			}
			set
			{
				this._fECHA_INICIO = value;
			}
		}
		
		private DateTime? _fECHA_FIN;
		public virtual DateTime? FECHA_FIN
		{
			get
			{
				return this._fECHA_FIN;
			}
			set
			{
				this._fECHA_FIN = value;
			}
		}
		
		private long _iD_HORARIO;
		public virtual long ID_HORARIO
		{
			get
			{
				return this._iD_HORARIO;
			}
			set
			{
				this._iD_HORARIO = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private string _cICLO;
		public virtual string CICLO
		{
			get
			{
				return this._cICLO;
			}
			set
			{
				this._cICLO = value;
			}
		}
		
		private Horario _horario;
		public virtual Horario Horario
		{
			get
			{
				return this._horario;
			}
			set
			{
				this._horario = value;
			}
		}
		
		private IList<Detalle_horario> _detalle_horarios = new List<Detalle_horario>();
		public virtual IList<Detalle_horario> Detalle_horarios
		{
			get
			{
				return this._detalle_horarios;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Pago
	{
		private long _iD_PAGO;
		public virtual long ID_PAGO
		{
			get
			{
				return this._iD_PAGO;
			}
			set
			{
				this._iD_PAGO = value;
			}
		}
		
		private DateTime? _fECHA;
		public virtual DateTime? FECHA
		{
			get
			{
				return this._fECHA;
			}
			set
			{
				this._fECHA = value;
			}
		}
		
		private string _cONCEPTO;
		public virtual string CONCEPTO
		{
			get
			{
				return this._cONCEPTO;
			}
			set
			{
				this._cONCEPTO = value;
			}
		}
		
		private string _sUBCONCEPTO;
		public virtual string SUBCONCEPTO
		{
			get
			{
				return this._sUBCONCEPTO;
			}
			set
			{
				this._sUBCONCEPTO = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private double? _cARGO;
		public virtual double? CARGO
		{
			get
			{
				return this._cARGO;
			}
			set
			{
				this._cARGO = value;
			}
		}
		
		private double? _pAGO_RECARGO;
		public virtual double? PAGO_RECARGO
		{
			get
			{
				return this._pAGO_RECARGO;
			}
			set
			{
				this._pAGO_RECARGO = value;
			}
		}
		
		private double? _rECARGO;
		public virtual double? RECARGO
		{
			get
			{
				return this._rECARGO;
			}
			set
			{
				this._rECARGO = value;
			}
		}
		
		private double? _pAGO_CARGO;
		public virtual double? PAGO_CARGO
		{
			get
			{
				return this._pAGO_CARGO;
			}
			set
			{
				this._pAGO_CARGO = value;
			}
		}
		
		private double? _sALDO;
		public virtual double? SALDO
		{
			get
			{
				return this._sALDO;
			}
			set
			{
				this._sALDO = value;
			}
		}
		
		private DateTime? _fECHA_PAGO;
		public virtual DateTime? FECHA_PAGO
		{
			get
			{
				return this._fECHA_PAGO;
			}
			set
			{
				this._fECHA_PAGO = value;
			}
		}
		
		private string _rEFERENCIA;
		public virtual string REFERENCIA
		{
			get
			{
				return this._rEFERENCIA;
			}
			set
			{
				this._rEFERENCIA = value;
			}
		}
		
		private string _cODIGO_ALUMNO_EN_INSTITUCION;
		public virtual string CODIGO_ALUMNO_EN_INSTITUCION
		{
			get
			{
				return this._cODIGO_ALUMNO_EN_INSTITUCION;
			}
			set
			{
				this._cODIGO_ALUMNO_EN_INSTITUCION = value;
			}
		}
		
		private long? _iD_NIVEL;
		public virtual long? ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private Alumno _alumno;
		public virtual Alumno Alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Nivel_educativo
	{
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private IList<Profesor> _profesors = new List<Profesor>();
		public virtual IList<Profesor> Profesors
		{
			get
			{
				return this._profesors;
			}
		}
		
		private IList<Materium> _materia = new List<Materium>();
		public virtual IList<Materium> Materia
		{
			get
			{
				return this._materia;
			}
		}
		
		private IList<Horario> _horarios = new List<Horario>();
		public virtual IList<Horario> Horarios
		{
			get
			{
				return this._horarios;
			}
		}
		
		private IList<Grupo> _grupos = new List<Grupo>();
		public virtual IList<Grupo> Grupos
		{
			get
			{
				return this._grupos;
			}
		}
		
		private IList<Calendario_escolar> _calendario_escolars = new List<Calendario_escolar>();
		public virtual IList<Calendario_escolar> Calendario_escolars
		{
			get
			{
				return this._calendario_escolars;
			}
		}
		
		private IList<Alumno> _alumnos = new List<Alumno>();
		public virtual IList<Alumno> Alumnos
		{
			get
			{
				return this._alumnos;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Modulo
	{
		private long _iD_MODULO;
		public virtual long ID_MODULO
		{
			get
			{
				return this._iD_MODULO;
			}
			set
			{
				this._iD_MODULO = value;
			}
		}
		
		private string _nOMBRE_MODULO;
		public virtual string NOMBRE_MODULO
		{
			get
			{
				return this._nOMBRE_MODULO;
			}
			set
			{
				this._nOMBRE_MODULO = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private string _uRL;
		public virtual string URL
		{
			get
			{
				return this._uRL;
			}
			set
			{
				this._uRL = value;
			}
		}
		
		private IList<Rol> _rols = new List<Rol>();
		public virtual IList<Rol> Rols
		{
			get
			{
				return this._rols;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Mes_escolar
	{
		private string _lISTA_DIAS_ACTIVIDAD;
		public virtual string LISTA_DIAS_ACTIVIDAD
		{
			get
			{
				return this._lISTA_DIAS_ACTIVIDAD;
			}
			set
			{
				this._lISTA_DIAS_ACTIVIDAD = value;
			}
		}
		
		private double? _mES_NRO;
		public virtual double? MES_NRO
		{
			get
			{
				return this._mES_NRO;
			}
			set
			{
				this._mES_NRO = value;
			}
		}
		
		private long? _iD_ACTIVIDAD;
		public virtual long? ID_ACTIVIDAD
		{
			get
			{
				return this._iD_ACTIVIDAD;
			}
			set
			{
				this._iD_ACTIVIDAD = value;
			}
		}
		
		private long? _iD_CALENDARIO;
		public virtual long? ID_CALENDARIO
		{
			get
			{
				return this._iD_CALENDARIO;
			}
			set
			{
				this._iD_CALENDARIO = value;
			}
		}
		
		private long? _iD_NIVEL;
		public virtual long? ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private Mes_actividad _mes_actividad;
		public virtual Mes_actividad Mes_actividad
		{
			get
			{
				return this._mes_actividad;
			}
			set
			{
				this._mes_actividad = value;
			}
		}
		
		private Calendario_escolar _calendario_escolar;
		public virtual Calendario_escolar Calendario_escolar
		{
			get
			{
				return this._calendario_escolar;
			}
			set
			{
				this._calendario_escolar = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Mes_actividad
	{
		private long _iD_ACTIVIDAD;
		public virtual long ID_ACTIVIDAD
		{
			get
			{
				return this._iD_ACTIVIDAD;
			}
			set
			{
				this._iD_ACTIVIDAD = value;
			}
		}
		
		private string _nOMBRE_ACTIVIDAD;
		public virtual string NOMBRE_ACTIVIDAD
		{
			get
			{
				return this._nOMBRE_ACTIVIDAD;
			}
			set
			{
				this._nOMBRE_ACTIVIDAD = value;
			}
		}
		
		private string _dESCRIPCION_ACTIVIDAD;
		public virtual string DESCRIPCION_ACTIVIDAD
		{
			get
			{
				return this._dESCRIPCION_ACTIVIDAD;
			}
			set
			{
				this._dESCRIPCION_ACTIVIDAD = value;
			}
		}
		
		private string _cOLOR_ACTIVIDAD;
		public virtual string COLOR_ACTIVIDAD
		{
			get
			{
				return this._cOLOR_ACTIVIDAD;
			}
			set
			{
				this._cOLOR_ACTIVIDAD = value;
			}
		}
		
		private IList<Mes_escolar> _mes_escolars = new List<Mes_escolar>();
		public virtual IList<Mes_escolar> Mes_escolars
		{
			get
			{
				return this._mes_escolars;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Mensajes_global_borrar
	{
		private long? _iD_MENSAJE;
		public virtual long? ID_MENSAJE
		{
			get
			{
				return this._iD_MENSAJE;
			}
			set
			{
				this._iD_MENSAJE = value;
			}
		}
		
		private long? _iD_PERSONA;
		public virtual long? ID_PERSONA
		{
			get
			{
				return this._iD_PERSONA;
			}
			set
			{
				this._iD_PERSONA = value;
			}
		}
		
		private long _iD;
		public virtual long ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private Mensaje _mensaje;
		public virtual Mensaje Mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				this._mensaje = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Mensaje
	{
		private long _iD_MENSAJE;
		public virtual long ID_MENSAJE
		{
			get
			{
				return this._iD_MENSAJE;
			}
			set
			{
				this._iD_MENSAJE = value;
			}
		}
		
		private string _mES;
		public virtual string MES
		{
			get
			{
				return this._mES;
			}
			set
			{
				this._mES = value;
			}
		}
		
		private string _aNIO;
		public virtual string ANIO
		{
			get
			{
				return this._aNIO;
			}
			set
			{
				this._aNIO = value;
			}
		}
		
		private string _pARA;
		public virtual string PARA
		{
			get
			{
				return this._pARA;
			}
			set
			{
				this._pARA = value;
			}
		}
		
		private string _dE;
		public virtual string DE
		{
			get
			{
				return this._dE;
			}
			set
			{
				this._dE = value;
			}
		}
		
		private string _aSUNTO;
		public virtual string ASUNTO
		{
			get
			{
				return this._aSUNTO;
			}
			set
			{
				this._aSUNTO = value;
			}
		}
		
		private string _lEIDO;
		public virtual string LEIDO
		{
			get
			{
				return this._lEIDO;
			}
			set
			{
				this._lEIDO = value;
			}
		}
		
		private string _iD_DE;
		public virtual string ID_DE
		{
			get
			{
				return this._iD_DE;
			}
			set
			{
				this._iD_DE = value;
			}
		}
		
		private string _tEXTO;
		public virtual string TEXTO
		{
			get
			{
				return this._tEXTO;
			}
			set
			{
				this._tEXTO = value;
			}
		}
		
		private IList<Mensajes_global_borrar> _mensajes_global_borrars = new List<Mensajes_global_borrar>();
		public virtual IList<Mensajes_global_borrar> Mensajes_global_borrars
		{
			get
			{
				return this._mensajes_global_borrars;
			}
		}
		
		private Destinatario _destinatario;
		public virtual Destinatario Destinatario
		{
			get
			{
				return this._destinatario;
			}
			set
			{
				this._destinatario = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Medico
	{
		private long _iD_MEDICO;
		public virtual long ID_MEDICO
		{
			get
			{
				return this._iD_MEDICO;
			}
			set
			{
				this._iD_MEDICO = value;
			}
		}
		
		private Persona _persona;
		public virtual Persona Persona
		{
			get
			{
				return this._persona;
			}
			set
			{
				this._persona = value;
			}
		}
		
		private IList<Historial_medico> _historial_medicos = new List<Historial_medico>();
		public virtual IList<Historial_medico> Historial_medicos
		{
			get
			{
				return this._historial_medicos;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Materia_prerrequisito
	{
		private long? _iD_MATERIA;
		public virtual long? ID_MATERIA
		{
			get
			{
				return this._iD_MATERIA;
			}
			set
			{
				this._iD_MATERIA = value;
			}
		}
		
		private long? _iD_NIVEL;
		public virtual long? ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private Materium _materium;
		public virtual Materium Materium
		{
			get
			{
				return this._materium;
			}
			set
			{
				this._materium = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Materia_grupo
	{
		private long _iD_GRUPO;
		public virtual long ID_GRUPO
		{
			get
			{
				return this._iD_GRUPO;
			}
			set
			{
				this._iD_GRUPO = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private long _iD_MATERIA;
		public virtual long ID_MATERIA
		{
			get
			{
				return this._iD_MATERIA;
			}
			set
			{
				this._iD_MATERIA = value;
			}
		}
		
		private long? _iD_PROFESOR;
		public virtual long? ID_PROFESOR
		{
			get
			{
				return this._iD_PROFESOR;
			}
			set
			{
				this._iD_PROFESOR = value;
			}
		}
		
		private Grupo _grupo;
		public virtual Grupo Grupo
		{
			get
			{
				return this._grupo;
			}
			set
			{
				this._grupo = value;
			}
		}
		
		private Materium _materium;
		public virtual Materium Materium
		{
			get
			{
				return this._materium;
			}
			set
			{
				this._materium = value;
			}
		}
		
		private Profesor _profesor;
		public virtual Profesor Profesor
		{
			get
			{
				return this._profesor;
			}
			set
			{
				this._profesor = value;
			}
		}
		
		private IList<Destinatario> _destinatarios = new List<Destinatario>();
		public virtual IList<Destinatario> Destinatarios
		{
			get
			{
				return this._destinatarios;
			}
		}
		
		private IList<Calificacion_parcial> _calificacion_parcials = new List<Calificacion_parcial>();
		public virtual IList<Calificacion_parcial> Calificacion_parcials
		{
			get
			{
				return this._calificacion_parcials;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Materium
	{
		private long _iD_MATERIA;
		public virtual long ID_MATERIA
		{
			get
			{
				return this._iD_MATERIA;
			}
			set
			{
				this._iD_MATERIA = value;
			}
		}
		
		private string _nOMBRE;
		public virtual string NOMBRE
		{
			get
			{
				return this._nOMBRE;
			}
			set
			{
				this._nOMBRE = value;
			}
		}
		
		private string _gRADO;
		public virtual string GRADO
		{
			get
			{
				return this._gRADO;
			}
			set
			{
				this._gRADO = value;
			}
		}
		
		private float? _cALIFICACION_APROBATORIA;
		public virtual float? CALIFICACION_APROBATORIA
		{
			get
			{
				return this._cALIFICACION_APROBATORIA;
			}
			set
			{
				this._cALIFICACION_APROBATORIA = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private string _cLAVE;
		public virtual string CLAVE
		{
			get
			{
				return this._cLAVE;
			}
			set
			{
				this._cLAVE = value;
			}
		}
		
		private Nivel_educativo _nivel_educativo;
		public virtual Nivel_educativo Nivel_educativo
		{
			get
			{
				return this._nivel_educativo;
			}
			set
			{
				this._nivel_educativo = value;
			}
		}
		
		private IList<Profesor> _profesors = new List<Profesor>();
		public virtual IList<Profesor> Profesors
		{
			get
			{
				return this._profesors;
			}
		}
		
		private IList<Materia_prerrequisito> _materia_prerrequisitos = new List<Materia_prerrequisito>();
		public virtual IList<Materia_prerrequisito> Materia_prerrequisitos
		{
			get
			{
				return this._materia_prerrequisitos;
			}
		}
		
		private IList<Materia_grupo> _materia_grupos = new List<Materia_grupo>();
		public virtual IList<Materia_grupo> Materia_grupos
		{
			get
			{
				return this._materia_grupos;
			}
		}
		
		private IList<Calificacion_parcial> _calificacion_parcials = new List<Calificacion_parcial>();
		public virtual IList<Calificacion_parcial> Calificacion_parcials
		{
			get
			{
				return this._calificacion_parcials;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Literal
	{
		private long _iD_LITERAL;
		public virtual long ID_LITERAL
		{
			get
			{
				return this._iD_LITERAL;
			}
			set
			{
				this._iD_LITERAL = value;
			}
		}
		
		private string _lITERAL;
		public virtual string LITERAL
		{
			get
			{
				return this._lITERAL;
			}
			set
			{
				this._lITERAL = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private int? _vALOR;
		public virtual int? VALOR
		{
			get
			{
				return this._vALOR;
			}
			set
			{
				this._vALOR = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Liga
	{
		private long _iD_LIGA;
		public virtual long ID_LIGA
		{
			get
			{
				return this._iD_LIGA;
			}
			set
			{
				this._iD_LIGA = value;
			}
		}
		
		private string _dESCRIPCION_LIGA;
		public virtual string DESCRIPCION_LIGA
		{
			get
			{
				return this._dESCRIPCION_LIGA;
			}
			set
			{
				this._dESCRIPCION_LIGA = value;
			}
		}
		
		private string _uRL_LIGA;
		public virtual string URL_LIGA
		{
			get
			{
				return this._uRL_LIGA;
			}
			set
			{
				this._uRL_LIGA = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Inasistencium
	{
		private long _iD_INASISTENCIA;
		public virtual long ID_INASISTENCIA
		{
			get
			{
				return this._iD_INASISTENCIA;
			}
			set
			{
				this._iD_INASISTENCIA = value;
			}
		}
		
		private string _iD_ALUMNO;
		public virtual string ID_ALUMNO
		{
			get
			{
				return this._iD_ALUMNO;
			}
			set
			{
				this._iD_ALUMNO = value;
			}
		}
		
		private long? _iD_PROFESOR;
		public virtual long? ID_PROFESOR
		{
			get
			{
				return this._iD_PROFESOR;
			}
			set
			{
				this._iD_PROFESOR = value;
			}
		}
		
		private long? _iD_MATERIA;
		public virtual long? ID_MATERIA
		{
			get
			{
				return this._iD_MATERIA;
			}
			set
			{
				this._iD_MATERIA = value;
			}
		}
		
		private string _dIA;
		public virtual string DIA
		{
			get
			{
				return this._dIA;
			}
			set
			{
				this._dIA = value;
			}
		}
		
		private string _mES;
		public virtual string MES
		{
			get
			{
				return this._mES;
			}
			set
			{
				this._mES = value;
			}
		}
		
		private string _yEAR;
		public virtual string YEAR
		{
			get
			{
				return this._yEAR;
			}
			set
			{
				this._yEAR = value;
			}
		}
		
		private string _cODIGO_ALUMNO_EN_INSTITUCION;
		public virtual string CODIGO_ALUMNO_EN_INSTITUCION
		{
			get
			{
				return this._cODIGO_ALUMNO_EN_INSTITUCION;
			}
			set
			{
				this._cODIGO_ALUMNO_EN_INSTITUCION = value;
			}
		}
		
		private long? _iD_NIVEL;
		public virtual long? ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private Alumno _alumno;
		public virtual Alumno Alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Horario
	{
		private long _iD_HORARIO;
		public virtual long ID_HORARIO
		{
			get
			{
				return this._iD_HORARIO;
			}
			set
			{
				this._iD_HORARIO = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private Nivel_educativo _nivel_educativo;
		public virtual Nivel_educativo Nivel_educativo
		{
			get
			{
				return this._nivel_educativo;
			}
			set
			{
				this._nivel_educativo = value;
			}
		}
		
		private IList<Periodo> _periodos = new List<Periodo>();
		public virtual IList<Periodo> Periodos
		{
			get
			{
				return this._periodos;
			}
		}
		
		private IList<Detalle_horario> _detalle_horarios = new List<Detalle_horario>();
		public virtual IList<Detalle_horario> Detalle_horarios
		{
			get
			{
				return this._detalle_horarios;
			}
		}
		
		private IList<Grupo> _grupos = new List<Grupo>();
		public virtual IList<Grupo> Grupos
		{
			get
			{
				return this._grupos;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Historial_medico
	{
		private long _iD_HISTORIAL;
		public virtual long ID_HISTORIAL
		{
			get
			{
				return this._iD_HISTORIAL;
			}
			set
			{
				this._iD_HISTORIAL = value;
			}
		}
		
		private string _dIA;
		public virtual string DIA
		{
			get
			{
				return this._dIA;
			}
			set
			{
				this._dIA = value;
			}
		}
		
		private string _mES;
		public virtual string MES
		{
			get
			{
				return this._mES;
			}
			set
			{
				this._mES = value;
			}
		}
		
		private string _aNIO;
		public virtual string ANIO
		{
			get
			{
				return this._aNIO;
			}
			set
			{
				this._aNIO = value;
			}
		}
		
		private string _dESCRIPCION_CITA;
		public virtual string DESCRIPCION_CITA
		{
			get
			{
				return this._dESCRIPCION_CITA;
			}
			set
			{
				this._dESCRIPCION_CITA = value;
			}
		}
		
		private string _pRESCRIPCION_MEDICA;
		public virtual string PRESCRIPCION_MEDICA
		{
			get
			{
				return this._pRESCRIPCION_MEDICA;
			}
			set
			{
				this._pRESCRIPCION_MEDICA = value;
			}
		}
		
		private string _tIEMPO_INCAPACIDAD;
		public virtual string TIEMPO_INCAPACIDAD
		{
			get
			{
				return this._tIEMPO_INCAPACIDAD;
			}
			set
			{
				this._tIEMPO_INCAPACIDAD = value;
			}
		}
		
		private long? _iD_MEDICO;
		public virtual long? ID_MEDICO
		{
			get
			{
				return this._iD_MEDICO;
			}
			set
			{
				this._iD_MEDICO = value;
			}
		}
		
		private string _cODIGO_ALUMNO_EN_INSTITUCION;
		public virtual string CODIGO_ALUMNO_EN_INSTITUCION
		{
			get
			{
				return this._cODIGO_ALUMNO_EN_INSTITUCION;
			}
			set
			{
				this._cODIGO_ALUMNO_EN_INSTITUCION = value;
			}
		}
		
		private long? _iD_NIVEL;
		public virtual long? ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private Medico _medico;
		public virtual Medico Medico
		{
			get
			{
				return this._medico;
			}
			set
			{
				this._medico = value;
			}
		}
		
		private Alumno _alumno;
		public virtual Alumno Alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Grupo
	{
		private long _iD_GRUPO;
		public virtual long ID_GRUPO
		{
			get
			{
				return this._iD_GRUPO;
			}
			set
			{
				this._iD_GRUPO = value;
			}
		}
		
		private string _nOMENCLATURA;
		public virtual string NOMENCLATURA
		{
			get
			{
				return this._nOMENCLATURA;
			}
			set
			{
				this._nOMENCLATURA = value;
			}
		}
		
		private double? _cUPO_MAXIMO;
		public virtual double? CUPO_MAXIMO
		{
			get
			{
				return this._cUPO_MAXIMO;
			}
			set
			{
				this._cUPO_MAXIMO = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private Nivel_educativo _nivel_educativo;
		public virtual Nivel_educativo Nivel_educativo
		{
			get
			{
				return this._nivel_educativo;
			}
			set
			{
				this._nivel_educativo = value;
			}
		}
		
		private IList<Horario> _horarios = new List<Horario>();
		public virtual IList<Horario> Horarios
		{
			get
			{
				return this._horarios;
			}
		}
		
		private IList<Tarea> _tareas = new List<Tarea>();
		public virtual IList<Tarea> Tareas
		{
			get
			{
				return this._tareas;
			}
		}
		
		private IList<Materia_grupo> _materia_grupos = new List<Materia_grupo>();
		public virtual IList<Materia_grupo> Materia_grupos
		{
			get
			{
				return this._materia_grupos;
			}
		}
		
		private IList<Alumno> _alumnos = new List<Alumno>();
		public virtual IList<Alumno> Alumnos
		{
			get
			{
				return this._alumnos;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Foto_alumno
	{
		private long _iD_FOTO;
		public virtual long ID_FOTO
		{
			get
			{
				return this._iD_FOTO;
			}
			set
			{
				this._iD_FOTO = value;
			}
		}
		
		private byte[] _fOTO;
		public virtual byte[] FOTO
		{
			get
			{
				return this._fOTO;
			}
			set
			{
				this._fOTO = value;
			}
		}
		
		private string _cODIGO_ALUMNO_EN_INSTITUCION;
		public virtual string CODIGO_ALUMNO_EN_INSTITUCION
		{
			get
			{
				return this._cODIGO_ALUMNO_EN_INSTITUCION;
			}
			set
			{
				this._cODIGO_ALUMNO_EN_INSTITUCION = value;
			}
		}
		
		private long? _iD_NIVEL;
		public virtual long? ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private Alumno _alumno;
		public virtual Alumno Alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Domicilio
	{
		private Char _tIPO_DOMICILIO;
		public virtual Char TIPO_DOMICILIO
		{
			get
			{
				return this._tIPO_DOMICILIO;
			}
			set
			{
				this._tIPO_DOMICILIO = value;
			}
		}
		
		private string _cALLE;
		public virtual string CALLE
		{
			get
			{
				return this._cALLE;
			}
			set
			{
				this._cALLE = value;
			}
		}
		
		private string _nUMERO_EXTERIOR;
		public virtual string NUMERO_EXTERIOR
		{
			get
			{
				return this._nUMERO_EXTERIOR;
			}
			set
			{
				this._nUMERO_EXTERIOR = value;
			}
		}
		
		private string _nUMERO_INTERIOR;
		public virtual string NUMERO_INTERIOR
		{
			get
			{
				return this._nUMERO_INTERIOR;
			}
			set
			{
				this._nUMERO_INTERIOR = value;
			}
		}
		
		private string _cOLONIA;
		public virtual string COLONIA
		{
			get
			{
				return this._cOLONIA;
			}
			set
			{
				this._cOLONIA = value;
			}
		}
		
		private string _mUNICIPIO;
		public virtual string MUNICIPIO
		{
			get
			{
				return this._mUNICIPIO;
			}
			set
			{
				this._mUNICIPIO = value;
			}
		}
		
		private string _eSTADO;
		public virtual string ESTADO
		{
			get
			{
				return this._eSTADO;
			}
			set
			{
				this._eSTADO = value;
			}
		}
		
		private string _pAIS;
		public virtual string PAIS
		{
			get
			{
				return this._pAIS;
			}
			set
			{
				this._pAIS = value;
			}
		}
		
		private string _cODIGO_POSTAL;
		public virtual string CODIGO_POSTAL
		{
			get
			{
				return this._cODIGO_POSTAL;
			}
			set
			{
				this._cODIGO_POSTAL = value;
			}
		}
		
		private long _iD_PERSONA;
		public virtual long ID_PERSONA
		{
			get
			{
				return this._iD_PERSONA;
			}
			set
			{
				this._iD_PERSONA = value;
			}
		}
		
		private Persona _persona;
		public virtual Persona Persona
		{
			get
			{
				return this._persona;
			}
			set
			{
				this._persona = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Detalle_horario
	{
		private string _dIA;
		public virtual string DIA
		{
			get
			{
				return this._dIA;
			}
			set
			{
				this._dIA = value;
			}
		}
		
		private DateTime? _hORA_INICIAL;
		public virtual DateTime? HORA_INICIAL
		{
			get
			{
				return this._hORA_INICIAL;
			}
			set
			{
				this._hORA_INICIAL = value;
			}
		}
		
		private DateTime? _hORA_FINAL;
		public virtual DateTime? HORA_FINAL
		{
			get
			{
				return this._hORA_FINAL;
			}
			set
			{
				this._hORA_FINAL = value;
			}
		}
		
		private long _iD_HORARIO;
		public virtual long ID_HORARIO
		{
			get
			{
				return this._iD_HORARIO;
			}
			set
			{
				this._iD_HORARIO = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private long _iD_PERIODO;
		public virtual long ID_PERIODO
		{
			get
			{
				return this._iD_PERIODO;
			}
			set
			{
				this._iD_PERIODO = value;
			}
		}
		
		private Horario _horario;
		public virtual Horario Horario
		{
			get
			{
				return this._horario;
			}
			set
			{
				this._horario = value;
			}
		}
		
		private Periodo _periodo;
		public virtual Periodo Periodo
		{
			get
			{
				return this._periodo;
			}
			set
			{
				this._periodo = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Destinatario
	{
		private long? _iD_PERSONA;
		public virtual long? ID_PERSONA
		{
			get
			{
				return this._iD_PERSONA;
			}
			set
			{
				this._iD_PERSONA = value;
			}
		}
		
		private long _iD_MENSAJE;
		public virtual long ID_MENSAJE
		{
			get
			{
				return this._iD_MENSAJE;
			}
			set
			{
				this._iD_MENSAJE = value;
			}
		}
		
		private long? _iD_GRUPO;
		public virtual long? ID_GRUPO
		{
			get
			{
				return this._iD_GRUPO;
			}
			set
			{
				this._iD_GRUPO = value;
			}
		}
		
		private long? _iD_NIVEL;
		public virtual long? ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private long? _iD_MATERIA;
		public virtual long? ID_MATERIA
		{
			get
			{
				return this._iD_MATERIA;
			}
			set
			{
				this._iD_MATERIA = value;
			}
		}
		
		private Persona _persona;
		public virtual Persona Persona
		{
			get
			{
				return this._persona;
			}
			set
			{
				this._persona = value;
			}
		}
		
		private Mensaje _mensaje;
		public virtual Mensaje Mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				this._mensaje = value;
			}
		}
		
		private Materia_grupo _materia_grupo;
		public virtual Materia_grupo Materia_grupo
		{
			get
			{
				return this._materia_grupo;
			}
			set
			{
				this._materia_grupo = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Circulare
	{
		private long _iD_CIRCULAR;
		public virtual long ID_CIRCULAR
		{
			get
			{
				return this._iD_CIRCULAR;
			}
			set
			{
				this._iD_CIRCULAR = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private string _pATH_ARCHIVO_CIRCULAR;
		public virtual string PATH_ARCHIVO_CIRCULAR
		{
			get
			{
				return this._pATH_ARCHIVO_CIRCULAR;
			}
			set
			{
				this._pATH_ARCHIVO_CIRCULAR = value;
			}
		}
		
		private DateTime? _fECHA;
		public virtual DateTime? FECHA
		{
			get
			{
				return this._fECHA;
			}
			set
			{
				this._fECHA = value;
			}
		}
		
		private long _iD_TUTOR;
		public virtual long ID_TUTOR
		{
			get
			{
				return this._iD_TUTOR;
			}
			set
			{
				this._iD_TUTOR = value;
			}
		}
		
		private Tutor _tutor;
		public virtual Tutor Tutor
		{
			get
			{
				return this._tutor;
			}
			set
			{
				this._tutor = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Calificacion_parcial
	{
		private long _iD_PARCIAL;
		public virtual long ID_PARCIAL
		{
			get
			{
				return this._iD_PARCIAL;
			}
			set
			{
				this._iD_PARCIAL = value;
			}
		}
		
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private string _cALIFICACION;
		public virtual string CALIFICACION
		{
			get
			{
				return this._cALIFICACION;
			}
			set
			{
				this._cALIFICACION = value;
			}
		}
		
		private long _iD_MATERIA;
		public virtual long ID_MATERIA
		{
			get
			{
				return this._iD_MATERIA;
			}
			set
			{
				this._iD_MATERIA = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private long _iD_GRUPO;
		public virtual long ID_GRUPO
		{
			get
			{
				return this._iD_GRUPO;
			}
			set
			{
				this._iD_GRUPO = value;
			}
		}
		
		private string _cODIGO_ALUMNO_EN_INSTITUCION;
		public virtual string CODIGO_ALUMNO_EN_INSTITUCION
		{
			get
			{
				return this._cODIGO_ALUMNO_EN_INSTITUCION;
			}
			set
			{
				this._cODIGO_ALUMNO_EN_INSTITUCION = value;
			}
		}
		
		private Materium _materium;
		public virtual Materium Materium
		{
			get
			{
				return this._materium;
			}
			set
			{
				this._materium = value;
			}
		}
		
		private Materia_grupo _materia_grupo;
		public virtual Materia_grupo Materia_grupo
		{
			get
			{
				return this._materia_grupo;
			}
			set
			{
				this._materia_grupo = value;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Calendario_escolar
	{
		private long _iD_CALENDARIO;
		public virtual long ID_CALENDARIO
		{
			get
			{
				return this._iD_CALENDARIO;
			}
			set
			{
				this._iD_CALENDARIO = value;
			}
		}
		
		private DateTime? _fECHA_INICIO;
		public virtual DateTime? FECHA_INICIO
		{
			get
			{
				return this._fECHA_INICIO;
			}
			set
			{
				this._fECHA_INICIO = value;
			}
		}
		
		private double? _tOTAL_SEMANAS;
		public virtual double? TOTAL_SEMANAS
		{
			get
			{
				return this._tOTAL_SEMANAS;
			}
			set
			{
				this._tOTAL_SEMANAS = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private DateTime? _fECHA_FIN;
		public virtual DateTime? FECHA_FIN
		{
			get
			{
				return this._fECHA_FIN;
			}
			set
			{
				this._fECHA_FIN = value;
			}
		}
		
		private Nivel_educativo _nivel_educativo;
		public virtual Nivel_educativo Nivel_educativo
		{
			get
			{
				return this._nivel_educativo;
			}
			set
			{
				this._nivel_educativo = value;
			}
		}
		
		private IList<Mes_escolar> _mes_escolars = new List<Mes_escolar>();
		public virtual IList<Mes_escolar> Mes_escolars
		{
			get
			{
				return this._mes_escolars;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Alumno
	{
		private string _cODIGO_ALUMNO_EN_INSTITUCION;
		public virtual string CODIGO_ALUMNO_EN_INSTITUCION
		{
			get
			{
				return this._cODIGO_ALUMNO_EN_INSTITUCION;
			}
			set
			{
				this._cODIGO_ALUMNO_EN_INSTITUCION = value;
			}
		}
		
		private long _iD_NIVEL;
		public virtual long ID_NIVEL
		{
			get
			{
				return this._iD_NIVEL;
			}
			set
			{
				this._iD_NIVEL = value;
			}
		}
		
		private long? _iD_PERSONA;
		public virtual long? ID_PERSONA
		{
			get
			{
				return this._iD_PERSONA;
			}
			set
			{
				this._iD_PERSONA = value;
			}
		}
		
		private Nivel_educativo _nivel_educativo;
		public virtual Nivel_educativo Nivel_educativo
		{
			get
			{
				return this._nivel_educativo;
			}
			set
			{
				this._nivel_educativo = value;
			}
		}
		
		private Persona _persona;
		public virtual Persona Persona
		{
			get
			{
				return this._persona;
			}
			set
			{
				this._persona = value;
			}
		}
		
		private IList<Tutor> _tutors = new List<Tutor>();
		public virtual IList<Tutor> Tutors
		{
			get
			{
				return this._tutors;
			}
		}
		
		private IList<Grupo> _grupos = new List<Grupo>();
		public virtual IList<Grupo> Grupos
		{
			get
			{
				return this._grupos;
			}
		}
		
		private IList<Solicitud_tramite> _solicitud_tramites = new List<Solicitud_tramite>();
		public virtual IList<Solicitud_tramite> Solicitud_tramites
		{
			get
			{
				return this._solicitud_tramites;
			}
		}
		
		private IList<Pago> _pagos = new List<Pago>();
		public virtual IList<Pago> Pagos
		{
			get
			{
				return this._pagos;
			}
		}
		
		private IList<Inasistencium> _inasistencia = new List<Inasistencium>();
		public virtual IList<Inasistencium> Inasistencia
		{
			get
			{
				return this._inasistencia;
			}
		}
		
		private IList<Historial_medico> _historial_medicos = new List<Historial_medico>();
		public virtual IList<Historial_medico> Historial_medicos
		{
			get
			{
				return this._historial_medicos;
			}
		}
		
		private IList<Foto_alumno> _foto_alumnos = new List<Foto_alumno>();
		public virtual IList<Foto_alumno> Foto_alumnos
		{
			get
			{
				return this._foto_alumnos;
			}
		}
		
	}
}
namespace DataAccessLayer	
{
	public partial class Administrativo
	{
		private string _dESCRIPCION;
		public virtual string DESCRIPCION
		{
			get
			{
				return this._dESCRIPCION;
			}
			set
			{
				this._dESCRIPCION = value;
			}
		}
		
		private long _iD_ADMINISTRATIVO;
		public virtual long ID_ADMINISTRATIVO
		{
			get
			{
				return this._iD_ADMINISTRATIVO;
			}
			set
			{
				this._iD_ADMINISTRATIVO = value;
			}
		}
		
		private long? _iD_PERSONA;
		public virtual long? ID_PERSONA
		{
			get
			{
				return this._iD_PERSONA;
			}
			set
			{
				this._iD_PERSONA = value;
			}
		}
		
		private Persona _persona;
		public virtual Persona Persona
		{
			get
			{
				return this._persona;
			}
			set
			{
				this._persona = value;
			}
		}
		
		private IList<Solicitud_tramite> _solicitud_tramites = new List<Solicitud_tramite>();
		public virtual IList<Solicitud_tramite> Solicitud_tramites
		{
			get
			{
				return this._solicitud_tramites;
			}
		}
		
	}
}
#pragma warning restore 1591
